springdoc:
  api-docs:
    path: /api-docs
    groups:
      enabled: true

  swagger-ui:
    path: /swagger-ui
    enabled: true
    display-request-duration: true

  cache:
    disabled: true
  override-with-generic-response: false

---
spring:
  config:
    activate:
      on-profile: local
    import:
      - db-local.yml
      
---
spring:
  config:
    activate:
      on-profile: dev
    import:
      - db-dev.yml

---
spring:
  config:
    activate:
      on-profile: prod
    import:
      - db-prod.yml
---
spring:
  config:
    activate:
      on-profile: test
    import:
    - db-test.yml
