springdoc:
  api-docs:
    path: /api-docs
    groups:
      enabled: true

  swagger-ui:
    path: /swagger-ui
    enabled: true
    display-request-duration: true

  cache:
    disabled: true
  override-with-generic-response: false

jwt:
  issuer: "basterdz"
  secret-key: "shoppershoppershoppershoppershoppershoppershoppershopper"
  expiry-seconds: 1728000

oauth:
  apple:
    iss: https://appleid.apple.com
    client-id: ENC(QqK9Fkgo7DTdWgfZpNQBpSg7ZYsD418QWNClHKjEENY=)
    nonce: "dfsdfadsfasdfasdfasdfasdfasdfasdfasdfdas"

spring:
  config:
    import:
      - firebase.yml

jasypt:
  encryptor:
    bean: jasyptStringEncryptor

logging:
  slack:
    webhook-uri: ENC(hQyfqoMma7ToATpXwx5vG42HD2OfLBpL6Cv0jLhlyq6M0hcOO3ch5ApWfiPedrk1Sw+5kg6Xh8QgoRRmoeom1W+OoABkJ+GxXtJKQ+KJlZkfdtaC8wDT3zNPGBRWnqTt)
  config: classpath:logback-spring.xml

---
spring:
  config:
    activate:
      on-profile: local
    import:
      - db-local.yml

---
spring:
  config:
    activate:
      on-profile: dev
    import:
      - db-dev.yml

---
spring:
  config:
    activate:
      on-profile: prod
    import:
      - db-prod.yml

---
spring:
  config:
    activate:
      on-profile: test
    import:
      - db-test.yml
