springdoc:
  api-docs:
    path: /api-docs
    groups:
      enabled: true

  swagger-ui:
    path: /swagger-ui
    enabled: true
    display-request-duration: true

  cache:
    disabled: true
  override-with-generic-response: false

jwt:
  issuer: "basterdz"
  secret-key: "shoppershoppershoppershoppershoppershoppershoppershopper"
  expiry-seconds: 1728000

oauth:
  apple:
    iss: https://appleid.apple.com
    client-id: ${CLIENT_ID}
    nonce: "dfsdfadsfasdfasdfasdfasdfasdfasdfasdfdas"

spring:
  config:
    import:
      - firebase.yml

---
spring:
  config:
    activate:
      on-profile: local
    import:
      - db-local.yml

---
spring:
  config:
    activate:
      on-profile: dev
    import:
      - db-dev.yml

---
spring:
  config:
    activate:
      on-profile: prod
    import:
      - db-prod.yml

logging:
  slack:
    webhook-uri: ${SLACK_URL_PROD}
  config: classpath:logback-spring.xml

---
spring:
  config:
    activate:
      on-profile: test
    import:
      - db-test.yml
