spring:
  config:
    activate:
      on-profile: local
    import:
      - db-local.yml
      
springdoc:
  api-docs:
    path: /api-docs
    groups:
      enabled: true

  swagger-ui:
    path: /swagger-ui
    enabled: true
    display-request-duration: true

  cache:
    disabled: true
---
spring:
  config:
    activate:
      on-profile: test
    import:
    - db-test.yml