spring:
  profiles:
    default: local
  config:
    import:
      - db-local.yml

springdoc:
  api-docs:
    path: /api-docs
    groups:
      enabled: true

  swagger-ui:
    path: /swagger-ui
    enabled: true
    display-request-duration: true

  cache:
    disabled: true
