springdoc:
  api-docs:
    path: /api-docs
    groups:
      enabled: true

  swagger-ui:
    path: /swagger-ui
    enabled: true
    display-request-duration: true

  cache:
    disabled: true
  override-with-generic-response: false

jwt:
  issuer: "basterdz"
  secret-key: "shoppershoppershoppershoppershoppershoppershoppershopper"
  expiry-seconds: 1728000

oauth:
  apple:
    iss: https://appleid.apple.com
    client-id: ENC(QqK9Fkgo7DTdWgfZpNQBpSg7ZYsD418QWNClHKjEENY=)
    nonce: "dfsdfadsfasdfasdfasdfasdfasdfasdfasdfdas"

---
spring:
  config:
    activate:
      on-profile: local
    import:
      - db-local.yml
      - firebase.yml
      
---
spring:
  config:
    activate:
      on-profile: dev
    import:
      - db-dev.yml
      - firebase.yml

---
spring:
  config:
    activate:
      on-profile: prod
    import:
      - db-prod.yml
      - firebase.yml
