version: '3.8'

services:
  mysql:
    image: mysql:8.0.33
    container_name: basterdz-mysql
    restart: always
    ports:
      - "33006:3306"
    environment:
      MYSQL_DATABASE: basterdzdb
      MYSQL_ROOT_PASSWORD: nophone
      TZ: "Asia/Seoul"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

  h2:
    image: oscarfonts/h2:latest
    container_name: basterdz-h2
    ports:
      - "1521:1521"
      - "8081:81"
    environment:
      H2_OPTIONS: -ifNotExists
    volumes:
      - ./h2/:/opt/h2-data
    restart: always