version: '3'

services:
  app:
    image: jm0514/basterdz-server
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - basterdz-network

networks:
  basterdz-network: