version: '3'

services:
  mysql:
    image: mysql:8.0.33
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: basterdzdb
      MYSQL_ROOT_PASSWORD: nophone
      TZ: "Asia/Seoul"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    networks:
      - basterdz-network

  app:
    image: stophwan/basterdz-server:0.0.1
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/basterdzdb?&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
      SPRING_DATASOURCE_USERNAME: root
      SPRINT_DATASOURCE_PASSWORD: nophone
    depends_on:
      - mysql
    networks:
      - basterdz-network

networks:
  basterdz-network:
