version: '3.8'

services:
  mysql:
    image: mysql:8.0.33
    container_name: basterdz-mysql
    restart: always
    ports:
      - "33006:3306"
    environment:
      MYSQL_DATABASE: basterdzdb
      MYSQL_ROOT_PASSWORD: nophone
      TZ: "Asia/Seoul"
    command:
      - --character-set-server=utf8
      - --collation-server=utf8_general_ci
