name: ci

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Create and move Firebase Admin SDK JSON file
        env:
          FIREBASE_ADMIN_SDK_JSON: ${{ secrets.FIREBASE_ADMIN_SDK_JSON }}
        run: |
          echo "${FIREBASE_ADMIN_SDK_JSON}" > basterdz-firebase-adminsdk.json
          mkdir -p dnd-10th-10-backend/basterdz-external/src/main/resources/firebase
          mv basterdz-firebase-adminsdk.json dnd-10th-10-backend/basterdz-external/src/main/resources/firebase/

      - name: Test with Gradle
        env:
          ENCRYPTOR_KEY: ${{ secrets.ENCRYPTOR_KEY }}
        run: |
          ./gradlew test